### ISSUE TITLE
hscript string to hyperscript virtualnode?

### ISSUE THREAD

**Issue by chrisabrams** [twilson63/html2hscript#9]
This script seems to do a great job of parsing the html to hscript, but hscript is returned as a string. How does the string then get converted into a virtual node?

[Hyperscript](https://github.com/dominictarr/hyperscript) seems to be a function - am I expected to `eval` the string returned? I actually tried `eval` but got a blank string back.

**Comment by chrisabrams** [comment]
Another way to ask this question: how would I run the output of this library in hyperscript?

**Comment by twilson63** [comment]
Hey Chris,

Good point, I wanted to rewrite the code emit part to use something like
`jison` to generate the js code: https://libraries.io/npm/jison - but I
have not had time, I would not recommend doing anything like eval, unless
you need to, then maybe use something like
https://github.com/codeschool/javascript-sandbox

I hope that helps, but I use it to provide
http://html2hscript.herokuapp.com/ with the conversion process in the
browser.

I am sorry if this does not help, but I don't have a great answer.

On Fri, Oct 9, 2015 at 1:26 PM, Chris Abrams notifications@github.com
wrote:

> Another way to ask this question: how would I run the output of this
> library in hyperscript?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/twilson63/html2hscript/issues/9#issuecomment-146938988
> .

## 

Tom Wilson
Jack Russell Software, A Tabula Rasa Healthcare Division
494 Wando Park Blvd
Mount Pleasant, SC  29464
Phone: 843-606-6484
Mobile: 843-469-5856
Email: tom@jackhq.com
Web: http://www.jackhq.com
Calendar:
http://www.google.com/calendar/embed?src=tom%40jackrussellsoftware.com&ctz=America/New_York
http://www.jackhq.com/calendar

This e-mail may contain information that is confidential, privileged or
otherwise protected from disclosure by the Health Insurance Portability and
Accountability Act (HIPAA) and other state and federal laws.  This
information is intended only for the individual names above.  Any review,
use disclosure or dissemination of this material is strictly prohibited.
If you receive this information in error, please notify CareKinesis
immediately at 888-974-2763 and delete the original at once.

**Comment by chrisabrams** [comment]
Thanks for the info.

Could you point me to the part of the code where you construct the string that is returned?

**Comment by twilson63** [comment]
It starts here for each element:

https://github.com/twilson63/html2hscript/blob/master/index.js#L81

Thanks

Tom

On Fri, Oct 9, 2015 at 1:42 PM, Chris Abrams notifications@github.com
wrote:

> Thanks for the info.
> 
> Could you point me to the part of the code where you construct the string?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/twilson63/html2hscript/issues/9#issuecomment-146942899
> .

## 

Tom Wilson
Jack Russell Software, A Tabula Rasa Healthcare Division
494 Wando Park Blvd
Mount Pleasant, SC  29464
Phone: 843-606-6484
Mobile: 843-469-5856
Email: tom@jackhq.com
Web: http://www.jackhq.com
Calendar:
http://www.google.com/calendar/embed?src=tom%40jackrussellsoftware.com&ctz=America/New_York
http://www.jackhq.com/calendar

This e-mail may contain information that is confidential, privileged or
otherwise protected from disclosure by the Health Insurance Portability and
Accountability Act (HIPAA) and other state and federal laws.  This
information is intended only for the individual names above.  Any review,
use disclosure or dissemination of this material is strictly prohibited.
If you receive this information in error, please notify CareKinesis
immediately at 888-974-2763 and delete the original at once.

**Comment by chrisabrams** [comment]
This guy seems to have found an interesting way: https://github.com/Matt-Esch/virtual-dom/issues/316

**Comment by twilson63** [comment]
@chrisabrams - this looks interesting too -> https://github.com/gf3/sandbox
